apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: nasa
  links:
    - url: https://www.nasa.gov/
      title: Homepage
      icon: documentation
      type: documentation
spec:
  type: organization
  profile:
    displayName: NASA
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nasa-swpc-exporter
  description: Prometheus exporter for data collected from NASA NOAA Space Weather Prediction Center.
  annotations:
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
  tags:
    - python
    - metrics
spec:
  domain: monitoring
  type: service
  dependsOn:
    - resource:nasa-noaa-swpc
  providesApis:
    - monitoring/prometheus-metric-api
  lifecycle: production
  owner: group:monitoring
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nasa-noaa-swpc
  description: NASA NOAA Space Weather Prediction Center
  links:
    - url: https://www.swpc.noaa.gov/
      title: Homepage
      icon: documentation
      type: documentation
spec:
  type: rest-api
  owner: group:nasa
